name: Publish

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Logseq Publish
        uses: pengx17/logseq-publish@0.1.7
        with:
          dest: www
          # Temporary until master gets heading block urls
          version: nightly@sha256:6f2916ba2302f202faef5daa462219f4dab0076b70aa831ef5df397b4816f245

      - name: Add .nojekyll file
        run: touch www/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: www
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
