name: Test

on:
  push:

jobs:
  nbb-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Run graph-validator tests
        uses: logseq/graph-validator@main
